baseURL = "https://www.ajimenez.es/"
languageCode = "en-us"
title = "Coding & Painting"
theme = "hyde-hyde"

[params]
    author = "Aitor Jiménez Yañez"
    authorimage = "img/avatar.jpg"
    description = "Personal blog about programming, painting and wargaming."

    dateformat = "January 2, 2006"
    themeColor = "theme-base-09"

[params.social]
    github = "leberechtreinhold"
    email = "aitor@ajimenez.es"

[[menu.main]]
    name = "Programming"
    weight = 100
    identifier = "programming"
    url = "/coding/"
    
[[menu.main]]
    name = "Art"
    weight = 150
    identifier = "art"
    url = "/art/"

[[menu.main]]
    name = "Wargames"
    weight = 200
    identifier = "wargames"
    url = "/wargames/"

[taxonomies]
	tag = "tags"